version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://lagoon_user:lagoon_password@db:5432/lagoon_timetracker
      - SESSION_SECRET=your-super-secret-session-key-change-in-production
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static:ro
    restart: unless-stopped
    networks:
      - lagoon-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=lagoon_timetracker
      - POSTGRES_USER=lagoon_user
      - POSTGRES_PASSWORD=lagoon_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lagoon_user -d lagoon_timetracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - lagoon-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@lagoon.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - lagoon-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  lagoon-network:
    driver: bridge